// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onrobtdyzakhnquevfvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ucm9idGR5emFraG5xdWV2ZnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwODc3NTcsImV4cCI6MjA1NjY2Mzc1N30.7tQ9HXG0xbD2UClCjrKuZZ5gbBYt5jSJrKLphu4IhF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);